branch-defaults:
  default:
    environment: Udagram-api-env
environment-defaults:
  Udagram-api-env:
    branch: null
    repository: null
global:
  application_name: udagram-api
  default_ec2_keyname: udacity
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
